export const newsArticles = [
  {
    id: 1,
    title: "New Product Launch: Revolutionary Tech Innovation",
    author: "John Doe",
    date: "2024-01-15",
    status: "published",
    views: 1234,
    category: "Technology",
  },
  {
    id: 2,
    title: "Company Wins Industry Award for Excellence",
    author: "Jane Smith",
    date: "2024-01-12",
    status: "published",
    views: 856,
    category: "Awards",
  },
  {
    id: 3,
    title: "Market Analysis: Q4 Performance Review",
    author: "Mike Johnson",
    date: "2024-01-10",
    status: "draft",
    views: 0,
    category: "Business",
  },
  {
    id: 4,
    title: "Upcoming Trade Show Participation",
    author: "Sarah Wilson",
    date: "2024-01-08",
    status: "scheduled",
    views: 423,
    category: "Events",
  },
];
