export const products = [
  {
    id: 1,
    name: "Wireless Bluetooth Headphones",
    category: "Electronics",
    price: 99.99,
    stock: 156,
    status: "active",
    rating: 4.5,
    sales: 234,
    image: "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg",
  },
  {
    id: 2,
    name: "Smart Fitness Tracker",
    category: "Wearables",
    price: 199.99,
    stock: 89,
    status: "active",
    rating: 4.2,
    sales: 156,
    image: "https://images.pexels.com/photos/1797104/pexels-photo-1797104.jpeg",
  },
  {
    id: 3,
    name: "Organic Coffee Beans",
    category: "Food & Beverage",
    price: 24.99,
    stock: 0,
    status: "out_of_stock",
    rating: 4.8,
    sales: 456,
    image: "https://images.pexels.com/photos/13836/pexels-photo-13836.jpeg",
  },
  {
    id: 4,
    name: "Premium Yoga Mat",
    category: "Fitness",
    price: 79.99,
    stock: 234,
    status: "active",
    rating: 4.6,
    sales: 123,
    image: "https://images.pexels.com/photos/4056723/pexels-photo-4056723.jpeg",
  },
  {
    id: 5,
    name: "Smartphone Case",
    category: "Accessories",
    price: 19.99,
    stock: 45,
    status: "low_stock",
    rating: 4.1,
    sales: 89,
    image: "https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg",
  },
  {
    id: 6,
    name: "LED Desk Lamp",
    category: "Home & Office",
    price: 49.99,
    stock: 178,
    status: "active",
    rating: 4.4,
    sales: 67,
    image: "https://images.pexels.com/photos/1714341/pexels-photo-1714341.jpeg",
  },
];
