export const categories = [
  {
    id: 1,
    name: "Electronics",
    description: "Electronic devices and gadgets",
    productCount: 45,
    status: "active",
    parent: null,
  },
  {
    id: 2,
    name: "Smartphones",
    description: "Mobile phones and accessories",
    productCount: 23,
    status: "active",
    parent: "Electronics",
  },
  {
    id: 3,
    name: "Laptops",
    description: "Computers and laptop accessories",
    productCount: 18,
    status: "active",
    parent: "Electronics",
  },
  {
    id: 4,
    name: "Clothing",
    description: "Apparel and fashion items",
    productCount: 78,
    status: "active",
    parent: null,
  },
  {
    id: 5,
    name: "Men's Clothing",
    description: "Clothing for men",
    productCount: 34,
    status: "active",
    parent: "Clothing",
  },
  {
    id: 6,
    name: "Women's Clothing",
    description: "Clothing for women",
    productCount: 44,
    status: "active",
    parent: "Clothing",
  },
  {
    id: 7,
    name: "Home & Garden",
    description: "Home improvement and garden supplies",
    productCount: 56,
    status: "active",
    parent: null,
  },
  {
    id: 8,
    name: "Books",
    description: "Books and educational materials",
    productCount: 234,
    status: "active",
    parent: null,
  },
  {
    id: 9,
    name: "Sports",
    description: "Sports equipment and accessories",
    productCount: 12,
    status: "inactive",
    parent: null,
  },
  {
    id: 10,
    name: "Health & Beauty",
    description: "Health and beauty products",
    productCount: 67,
    status: "active",
    parent: null,
  },
];
